Save docs
machine-intelligence-laboratory/text_categorization pull request #12
Opened 2022-03-31 07:50 UTC by aby2s

2022-03-31 11:16 UTC, Guince requested changes

2022-03-31 11:16 UTC, Guince commented on ap/train/data_manager.py
> +        self.train_dict: typing.Dict[str, str] = joblib.load(self._config["train_dict_path"])
@aby2s Коля, мы с тобой говорили, что файлы joblib неудобные, т.к. в них нельзя дописывать в конец без того, чтобы сначала прочитать файл целиком. Поэтому я изменила joblib файл на txt файл. 
Файл в конфиге сейчас выглядит так: `train_vw_path: '/data/datasets/Antiplagiat/train_with_combined_grnti_69_rubric.txt'`

Поэтому мне кажется это лишнее изменение.

2022-03-31 11:16 UTC, Guince commented on ap/train/data_manager.py
> -        self._vw_dict = joblib.load(os.path.join(data_dir, "train_dict.joblib"), mmap_mode='r+')
А вот это как раз нужное изменение, ведь мы отказались от joblib файлов, это какой-то рудимент.

2022-03-31 11:16 UTC, Guince commented on ap/train/data_manager.py
> -    def generate_batches_balanced_by_rubric(self) -> artm.BatchVectorizer:
ты удалил это из за ипорта artm, да?

2022-03-31 11:16 UTC, Guince commented on ap/train/data_manager.py
>          if not all(
Коля, от нас в будущем требуют документацию, лучше её сразу писать. Напиши пожалуйста докстинг к этой функции.

2022-03-31 11:16 UTC, Guince commented on ap/train/data_manager.py
>          if not all(
С описанием типов входных и выходных параметров.

2022-03-31 11:16 UTC, Guince commented on ap/train/server.py
>      ) -> AddDocumentsToModelResponse:
И тут тоже нужен док стринг) Вообще можешь написать везде где не лень.

2022-03-31 11:16 UTC, Guince commented on ap/train/trainer.py
> -from topicnet.cooking_machine import rel_toolbox_lite
Используеся на 111 строчке и дальше, кажется не надо удалять.

2022-03-31 11:16 UTC, Guince commented on ap/utils/general.py
> +    res = {}
тоже докстринг

2022-04-01 08:05 UTC, aby2s commented on ap/train/data_manager.py
> +        self.train_dict: typing.Dict[str, str] = joblib.load(self._config["train_dict_path"])
Если трейн дикт это те же самые данные из другого формата, то надо это выкинуть. Я думал, это что-то другое.

2022-04-01 08:06 UTC, aby2s commented on ap/train/data_manager.py
> -    def generate_batches_balanced_by_rubric(self) -> artm.BatchVectorizer:
Я вот это удалил `-> artm.BatchVectorizer` - так нельзя из-за импортов (

2022-04-06 10:11 UTC, Guince commented on ap/train/data_manager.py
> +        self.train_dict: typing.Dict[str, str] = joblib.load(self._config["train_dict_path"])
Да, это те же самые данные. Сейчас код организован так, что считывается txt файл, где строка - это один документ в формате vw. Потом из этого файла создаётся train_dict - словарь, где ключ - id документа, значения - документ в vw формате.

При этом считанный txt файл не является атрибутом класса, так что не занимает память.

То есть лучше оставить как было, мне так кажется.

2022-04-06 11:55 UTC, Guince approved these changes

2022-04-07 07:44 UTC, merged