Add docs
machine-intelligence-laboratory/text_categorization pull request #31
Opened 2022-05-27 09:42 UTC by aby2s

2022-05-30 12:29 UTC, Guince requested changes

2022-05-30 12:29 UTC, Guince commented on ap/train/data_manager.py
> +def batch_names(starts_from, count) -> typing.Generator[str, None, None]:
Зачем? Можно же `from ap.utils.general import batch_names`

2022-05-30 12:29 UTC, Guince commented on ap/train/data_manager.py
> +        if os.path.exists(self.new_background_path):
Зачем эта проверка?
Может ты хотел сделать ensure_directory(self.new_background_path), чтобы создать эту папку, если её нет?

2022-05-31 13:12 UTC, Guince commented on ap/train/data_manager.py
> +def batch_names(starts_from, count) -> typing.Generator[str, None, None]:
и нужно. я проверила - эти функции идентичны.

2022-05-31 13:15 UTC, aby2s commented on ap/train/data_manager.py
> +        if os.path.exists(self.new_background_path):
ну если не добавляли документов без тем, то и не будет их

2022-05-31 14:05 UTC, merged